### ISSUE TITLE
Android: Switch to official "sentry-java/sentry-android" library 

### ISSUE THREAD

**Issue by msgitter** [danielgek/nativescript-sentry#11]
[sentry-android](https://github.com/joshdholtz/Sentry-Android) seems deprecated.
Are there any plans to switch to official [sentry-java/sentry-android](https://github.com/getsentry/sentry-java/tree/master/sentry-android) for Android?

**Comment by bradmartin** [comment]
In June of 2017 - this plugin added the sentry-android lib from Sentry. The one you referenced I have not found in the `history` of the `include.gradle` file for this plugin so it likely was never being utilized in this plugin. Daniel would know for certain but the `compile...` lines in the `platforms/android/include.gradle` would indicate if it was used at some time in the past and I do not see it.
