### ISSUE TITLE
Why is level not a valid sentry option?

### ISSUE THREAD

**Issue by jpakulski** [danielgek/nativescript-sentry#13]
According to Sentry [docs](https://docs.sentry.io/clients/elixir/usage/#optional-attributes) level is a valid option.

However it's commented out in the SentryOptions and SentryBreadcrumb interfaces.

What is the reason for this?

Thank You.

**Comment by bradmartin** [comment]
Think it's just not been abstracted yet. I have a fork going right now and this is something I'm about to work on 👍 - a long with various other changes. I'll ping @danielgek and see what he thinks about the direction of the fork and if we can plan some merging along the way.

**Comment by danielgek** [comment]
thanks @bradmartin, this has been released as 1.6.1 ;)
