### ISSUE TITLE
Not load class org.slf4j.impl.StaticLoggerBinder

### ISSUE THREAD

**Issue by MrCalamitus** [danielgek/nativescript-sentry#16]
In android show next message 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I solved with add line in include.gradle compile 'org.slf4j:slf4j-nop:1.7.25'

**Comment by danielgek** [comment]
please take a look at #12
