### ISSUE TITLE
Cannot read property 'getPackageManager' of undefined

### ISSUE THREAD

**Issue by Taronyuu** [danielgek/nativescript-sentry#18]
I tried to install this package but the moment I call `Sentry.init()` it throws the following error:

> TypeError: Cannot read property 'getPackageManager' of undefined
<img width="1163" alt="screenshot 2018-11-04 at 11 48 29" src="https://user-images.githubusercontent.com/7033142/47963113-8e447e80-e027-11e8-89c6-7c63576d33f0.png">

The code:
```javascript
Sentry.init("https://<mykey>:@sentry.io/<project>", {
    environment: settings.environment,
    release: 'v0.0.1',
});
```

As you can see I already added the current workaround of adding a ':' after they key as said in #15. I also tried to set the 'release' hoping that would solve this issue. But that didn't work either. As far as I can see there aren't any other issues about this problem, also Google didn't help much. And neither did SO. :)

```
$ tns --version
4.2.4

$ node -v
v10.11.0

$ npm -v
6.4.1
```

**Comment by danielgek** [comment]
should be fixed in the latest version
