### ISSUE TITLE
Nativescript-angular typescript problem

### ISSUE THREAD

**Issue by ghost** [danielgek/nativescript-sentry#2]
Hi I wan't to use this plugin in my project but when I import { SentryModule } from 'nativescript-sentry'; I have a typescript error. No Module exported. I try var SentryModule = require('nativescript-sentry') but this is error no forRoot function.
Please help what is the problem in typescript version?

Thanx Miklos

**Comment by danielgek** [comment]
@bumbella  try ` import { SentryModule } from 'nativescript-sentry/angular'`, got to update the readme xD

**Comment by danielgek** [comment]
@bumbella sorry just edited with working version

**Comment by ghost** [comment]
I get this error:
Error:(42, 10) TS2305:Module '"/Users/xxx/node_modules/nativescript-sentry/index"' has no exported member 'SentryModule'.

**Comment by danielgek** [comment]
@bumbella you got to add `/angular` on `import { SentryModule } from 'nativescript-sentry'`

**Comment by ghost** [comment]
I don't understand please write me what must have in code?

**Comment by danielgek** [comment]
you have `import { SentryModule } from 'nativescript-sentry'`
but you should have `import { SentryModule } from 'nativescript-sentry/angular'`

**Comment by ghost** [comment]
Thanx it start build tns run android but this error get:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformResourcesWithMergeJavaResForF0F1F2F3F4F5F6F7F8F9F10Debug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
        File1: /Users/mikloshumli/Development/Praktiker/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/11.4.2/jars/classes.jar
        File2: /Users/mikloshumli/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.8.7/8b46f39c78476fb848c81a49fa807a9e9506dddd/jackson-core-2.8.7.jar
```

**Comment by ghost** [comment]
thanx for your help. All works fine
I must insert gradle file
 dependencies {
  compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.21'
}

and 

andoid{
packagingOptions {
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/NOTICE'
  }
}

Have a nice day
Miklos

**Comment by danielgek** [comment]
humm estrange, i will take a look at this, thanks for the feedback ;)

**Comment by danielgek** [comment]
@bumbella you don't need to add `org.slf4j`(that is only needed when you use log4j, which is not the case ), i just update the plugin can you check if the problem still exists ?
