### ISSUE TITLE
Angular demo app not working

### ISSUE THREAD

**Issue by digitalhurricane-io** [danielgek/nativescript-sentry#20]
I get this error when trying to run the demo app:

System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demong/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: 
System.err: Error: Can't resolve all parameters for SentryErrorHandler: (?).
System.err: File: "file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 11175, column: 16
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err: 	Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 1098, column: 21
System.err: 	Frame: function:'CompileMetadataResolver._getDependenciesMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10987, column: 39
System.err: 	Frame: function:'CompileMetadataResolver._getTypeMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10880, column: 30
System.err: 	Frame: function:'CompileMetadataResolver._getInjectableTypeMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11102, column: 25
System.err: 	Frame: function:'CompileMetadataResolver.getProviderMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11111, column: 26
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11049, column: 53
System.err: 	Frame: function:'CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11009, column: 23
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10632, column: 76
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10623, column: 53
System.err: 	Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23932, column: 55
System.err: 	Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23913, column: 40
System.err: 	Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23873, column: 41
System.err: 	Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 202, column: 35
System.err: 	Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4414, column: 29
System.err: 	Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/platform-common.js', line: 85, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/platform-common.js', line: 148, column: 19
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err: 	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 884, column: 17
System.err: 	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 817, column: 28
System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 691, column: 14
System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err: 
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: 
System.err: Error: Can't resolve all parameters for SentryErrorHandler: (?).
System.err: File: "file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 11175, column: 16
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err: 	Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 1098, column: 21
System.err: 	Frame: function:'CompileMetadataResolver._getDependenciesMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10987, column: 39
System.err: 	Frame: function:'CompileMetadataResolver._getTypeMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10880, column: 30
System.err: 	Frame: function:'CompileMetadataResolver._getInjectableTypeMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11102, column: 25
System.err: 	Frame: function:'CompileMetadataResolver.getProviderMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11111, column: 26
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11049, column: 53
System.err: 	Frame: function:'CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 11009, column: 23
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10632, column: 76
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10623, column: 53
System.err: 	Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23932, column: 55
System.err: 	Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23913, column: 40
System.err: 	Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 23873, column: 41
System.err: 	Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 202, column: 35
System.err: 	Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4414, column: 29
System.err: 	Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/platform-common.js', line: 85, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/platform-common.js', line: 148, column: 19
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err: 	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 884, column: 17
System.err: 	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 817, column: 28
System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 691, column: 14
System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.demong/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err: 	at android.app.Activity.performCreate(Activity.java:7009)
System.err: 	at android.app.Activity.performCreate(Activity.java:7000)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
System.err: 	... 9 more

**Comment by dottodot** [comment]
Same here.

**Comment by Basim-Elayan** [comment]
Same here related to issue #23

**Comment by danielgek** [comment]
fixed in 1.7.1
