### ISSUE TITLE
Why limit setContextExtra to string values only?

### ISSUE THREAD

**Issue by jerbob92** [danielgek/nativescript-sentry#22]
Hello,

Thanks for this plugin!
I'm currently trying to add extra context data with ```Sentry.setContextExtra```, but both native environments try to cast the values to string (```extra as NSDictionary<string, string>``` for iOS, ```sentryClient.addExtra(key, extra[key].toString());``` for Android). Why? Sentry does support data structures in both native libraries.

It also would be very useful if we could use the option to add extra data to the user.
Both libraries support this:
https://github.com/getsentry/sentry-java/blob/master/sentry/src/main/java/io/sentry/event/UserBuilder.java (setData)

https://github.com/getsentry/sentry-cocoa/blob/cf20875d74904708d86fdfe9fa13aa6e03380e52/Sources/Sentry/SentryUser.m (extra)

**Comment by bradmartin** [comment]
I think I worked on this part of the plugin last year.

I don't recall why I used `string` there. It might be the way that Sentry was showing the data in their UI. If it wasn't a string it ended up not being helpful when looking at the data on Sentry's logs. Hope that helps with some of the understanding. I could be recalling the scenario wrong, it's been many months 😄 

The Sentry team seemed very excited about having NativeScript supported and they were open to making changes to their SDKs to improve the logs. So maybe this is something they'd be open to having a discussion about.

**Comment by jerbob92** [comment]
Thanks for your reply! I'm sure that's the Sentry UI is able to display data structures fine, I already use it on another project that uses the JavaScript sentry plugin.

**Comment by bradmartin** [comment]
Possibly, it may have been what I was trying to send 😄 and not anything wrong with Sentry or the SDKs

**Comment by bradmartin** [comment]
If I get some down time I'll try to run a test and see what it logs and make a PR 👍

**Comment by bradmartin** [comment]
@jerbob92 - I just tested it, the method `withExtra` on android expected a `java.lang.Object` and passing a number threw an exception so I just got around it by using string. I didn't have the time to implement it otherwise last year.

Sentry seems to do a good job displaying the values formatted regardless of them being `string`
![extra](https://user-images.githubusercontent.com/6006148/51994562-ad13af00-2476-11e9-87c5-335b21fefc6c.png)

**Comment by bradmartin** [comment]
@jerbob92 - I made an adjustment to locally test not passing a string but it seems that Sentry ends up taking a `java.lang.Integer` and making it a string as a the `raw` value on their end.

```
  for (const [key, value] of Object.entries(options.tags)) {
        console.log('adding key to event EXTRA', key, value);
        if (!isNaN(value)) {
          console.log('value is a number so using Integer', value);
          event.withExtra(key, new java.lang.Integer(value));
        } else {
          event.withExtra(key, value);
        }
      }
``` 
So here I did:
```typescript
 Sentry.captureException(error, {
      tags: {
        exception: 17227,
        brad: 'martin_brad_martin'
      },
      extra: {
        extra_number: 1,
        extra_string: 'oh snap!'
      }
    });
```

and the resulting Sentry log extras looked like this:
![raw](https://user-images.githubusercontent.com/6006148/51999092-a3427980-247f-11e9-981d-0d5e8ada74bf.png)

**Comment by bradmartin** [comment]
So I'll make a PR not to use `toString()` on numbers for now... but I'm not sure why Sentry still takes a java `Integer` as a `"1"` in the raw value.

**Comment by bradmartin** [comment]
Okay, I was wrong, the log wasn't updating because it matched a previous attempt. So doing this will allow numbers to work. I'll make the PR to improve that for now.

![rawnumber](https://user-images.githubusercontent.com/6006148/51999728-02ed5480-2481-11e9-9233-2bce8f7c1584.png)

**Comment by bradmartin** [comment]
@jerbob92 sorry to keep blowing you up, but this PR https://github.com/danielgek/nativescript-sentry/pulls will improve the logs for `extras` and fixes iOS bug not logging extras 👍

**Comment by jerbob92** [comment]
Hi @bradmartin no problem! Great work, thanks! However, this still only supports a few types. Here's what the UI for a raven-js project looks like when you add embedded objects: 
![image](https://user-images.githubusercontent.com/1312921/52037171-8add6800-252e-11e9-801c-3ad3b5782151.png)

This is from raven-js, with the method `Raven.setUserContext({})`. The signature of the method is:
```
setUserContext(user?: {
      [key: string]: any;
    })
```
Which is kinda like `Map<String, Object>` in the Android library I suppose. 

Note that this is under the section "User", not additional data. There might be a difference between User Context extra and the Additional Data of an event.

Possibly we can make some JS to Android serializer? Something like this:
```
  private static _convertDataTypeToJavaObject(value) {
    if (value === null) {
      return null;
    }

    switch (typeof value) {
      case 'object':
        if (value instanceof Date) {
          return new java.lang.String(value.toISOString());
        }

        if (Array.isArray(value)) {
          const nativeList = new java.util.ArrayList();
          value.forEach(data => {
            nativeList.add(this._convertDataTypeToJavaObject(data));
          });
          return nativeList;
        }

        const nativeObject = new java.util.HashMap<>();
        Object.keys(value).forEach(itemKey => {
          nativeObject.put(itemKey, this._convertDataTypeToJavaObject(value[itemKey]));
        });

        return nativeObject;
      case 'number':
        if (this.numberIs64Bit(value)) {
          if (this.numberHasDecimals(value)) {
            return new java.lang.Double(value);
          } else {
            return new java.lang.Long(value);
          }
        } else {
          if (this.numberHasDecimals(item)) {
            return new java.lang.Float(value);
          } else {
            return new java.lang.Integer(value);
          }
        }
      case 'boolean':
        return new java.lang.Boolean(value);
    }

    return new java.lang.String(value);
  }

  private static numberHasDecimals(value: number) {
    return !(value % 1 === 0);
  }

  private static numberIs64Bit(value: number) {
    return value < -Math.pow(2, 31) + 1 || value > Math.pow(2, 31) - 1;
  }
```

**Comment by bradmartin** [comment]
Awesome. That's a much more refined approach to handling the values 👍 - You should definitely submit that as a PR to piggyback my latest changes.  Or do you want me to make the change to my PR. I don't mind either way. Your contribution though 😄

**Comment by bradmartin** [comment]
As for the user on Android it's currently:

### android
```typescript
   const userNative = new io.sentry.event.UserBuilder()
      .setId(user.id)
      .setEmail(user.email ? user.email : '')
      .setUsername(user.username ? user.username : '')
      .build();

    io.sentry.Sentry.getStoredClient()
      .getContext()
      .setUser(userNative);
```

### ios 
Might need changes to handle nested data structure
```typescript
  public static setContextUser(user: SentryUser) {
    const userNative = SentryUser.alloc().initWithUserId(user.id);
    userNative.email = user.email ? user.email : '';
    userNative.username = user.username ? user.username : '';
    if (user.data) {
      // create NSDictionary<string, any> for the object provided
      const dict = NSDictionary.dictionaryWithDictionary(user.data as NSDictionary<string, any>);
      userNative.extra = dict ? dict : null;
    }
    SentryClient.sharedClient.user = userNative;
  }
```

Since the builder provides the `setData(Map<>)` and `withData(key, value)` methods. It should be fairly simple to take your converter and add the `data` to the UserBuilder so it would then be feature complete it looks like.

So this might work:

```typescript
 // handle the data object if provided
    let nativeMapObject: java.util.HashMap<any, any>;

    if (user.data) {
      nativeMapObject = new java.util.HashMap<any, any>();
      // map the data
      Object.keys(user.data).forEach(key => {
        // adding type check to not force toString on the extra
        // @link: https://github.com/danielgek/nativescript-sentry/issues/22
        const nativeDataValue = Sentry._convertDataTypeToJavaObject(user.data[key]);
        nativeMapObject.put(key, nativeDataValue);
      });
    }

    const userNative = new io.sentry.event.UserBuilder()
      .setId(user.id)
      .setEmail(user.email ? user.email : '')
      .setUsername(user.username ? user.username : '')
      .setData(nativeMapObject)
      .build();

    io.sentry.Sentry.getStoredClient()
      .getContext()
      .setUser(userNative);
```

Thoughts? Prob could use a ternary in the `setData` method but that looks like it might be good to go with your converter handling the data types.

**Comment by danielgek** [comment]
wow, awesome work guys !! will be review and releasing on this weekend !

**Comment by danielgek** [comment]
@jerbob92 tested your function(just needed a typo fix) and it works great, as @bradmartin said, do you want to summit a pr or can Brad add to this one ?

**Comment by jerbob92** [comment]
Great! I'm currently too busy to create a PR, deadlines....
So it's fine if Brad can add it to his one. Do we also need a converted method for iOS?

**Comment by bradmartin** [comment]
I'll run a test on both sides to confirm everything looks good to sentry

**Comment by danielgek** [comment]
@bradmartin awesome, i tested it and it appears to be working fine, but i would appreciate if you can verify it too(tow pair of eyes is better than one :P ) ;)

**Comment by bradmartin** [comment]
@danielgek - looks good to me 👍 

I tried updating angular demo, but the SentryErrorHandler might need a change to resolve correctly.

**Comment by bradmartin** [comment]
Just noticed you did AOT fix on the demo 👍 - maybe that was part of my issue.

**Comment by danielgek** [comment]
yeah yesterday i was able to fix it and actually released a small bump version, will take a look at this in a few hours ;)

**Comment by danielgek** [comment]
new version out ;)

**Comment by jerbob92** [comment]
Great work guys!
I just tested it out and I noticed one issue:
When a value is undefined, the code errors out, I think the fix would be to change the following line:
```
    if (value === null) {
      return null;
    }
```
(on https://github.com/danielgek/nativescript-sentry/blob/master/src/sentry.android.ts#L165)

To:
```
    if (typeof(value) === 'undefined' || value === null) {
      return null;
    }
```

The error was: `Error: java.lang.NullPointerException: toCopy == null`

**Comment by jerbob92** [comment]
I'm manually stripping out undefined values for now in my own code, this is what it looks like in Sentry now:
![image](https://user-images.githubusercontent.com/1312921/52163056-f8c79200-26dc-11e9-8467-c26b49e436ab.png)

Awesome! :tada:
