### ISSUE TITLE
Setting "extra" data to the exception

### ISSUE THREAD

**Issue by bozhidarc** [danielgek/nativescript-sentry#3]
Hi, I'm trying to add extra data to the caught exception through the extra field of `SentryClient` or `SentryClient.sharedClient`, but without any success.
Where is the right place to set the `extra` property?
```
SentryClient.sharedClient.extra.setValueForKey(
			"username",
			"[my username]"
		);
```

**Comment by danielgek** [comment]
@bozhidarc currently i haven't implemented that feature

but you can check [this generated defenitions](https://github.com/danielgek/nativescript-sentry/blob/bump-a-lot/src/sentry-api.ios.d.ts#L161) and use code a NS Dictionary like this:

```typescript
event.extra = NSDictionary.alloc<string, string>().initWithObjectsForKeys(
    utils.ios.collections.jsArrayToNSArray(['value1', 'value2']) as NSArray<string>,
    utils.ios.collections.jsArrayToNSArray(['key1', 'key2']) as NSArray<string>
);
```

i can implement it, but only in a few days

disclaimer: haven't testes the above code

**Comment by bozhidarc** [comment]
I managed to set the `extra` with the code bellow, but it doesn't work for the `user` property. I'm not sure why because it doesn't throw any errors.
I trie with your code but doesn't work. If you can integrated it will be great :)

```typescript
SentryClient.sharedClient.extra = {
	username: '',
	email: '',
};
```

**Comment by danielgek** [comment]
I think sentry has something like `.setUser`, it should be on the defenitions, I will look into it in the next few days ;)

**Comment by danielgek** [comment]
@bozhidarc just released a new version, check the readme for new(implemented a bunch of things)!

**Comment by bozhidarc** [comment]
Great, I will!
