### ISSUE TITLE
Cannot read property 'split' of undefined (Android runtime error)

### ISSUE THREAD

**Issue by piotrilski** [danielgek/nativescript-sentry#5]
Hey @danielgek,
First of all, thanks for your work.
I've just updated to 1.5.0, after sorting out a few issues related to the older version of typescript I have installed on my machine, I've found this error (runtime, Android):
`
JS: ns-renderer: Cannot read property 'split' of undefined
JS: 
JS: TypeError: Cannot read property 'split' of undefined
JS:     at Function.Common._init (file:///data/data/MYAPP/files/app/tns_modules/nativescript-sentry/sentry.common.js:25:27)
JS:     at Function.Sentry.init (file:///data/data/MYAPP/files/app/tns_modules/nativescript-sentry/sentry.js:12:14)
`

The way I'm trying to initialize it is:
`
Sentry.init('https://A_HASH_NUMBER@app.getsentry.com/A_NUMBER, {});
`

**Comment by danielgek** [comment]
@piotrilski you have to use the dsn with private and public keys  `Sentry.init('https://A_HASH_NUMBER:A_HASH_NUMBER@app.getsentry.com/A_NUMBER, {});`

**Comment by piotrilski** [comment]
Thanks!

**Comment by cerireyhan** [comment]
@danielgek I have the same error with Angular app however I add the key in app.module just like in the demo. Do you have a suggestion?
